version: '3'

services:
    postgres-db:
        image: postgres:12.4-alpine
        container_name: treninoo-db
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=treninoo-db
